name: ahoj

environment:
  sdk: '^2.18.6'
  
dependencies:
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  owoify_dart: ^2.0.1
  injectable: ^2.1.0
  get_it: ^7.2.0
  envied: ^0.3.0
  
dev_dependencies: 
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  envied_generator: ^0.3.0